language: cpp
sudo: false
os: linux
dist: trusty
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - openmpi-bin
            - libopenmpi-dev

env:
    # test single node/rank with different threading back ends
    - BUILD_NAME=serial   WITH_THREAD=serial   WITH_DISTRIBUTED=serial
    - BUILD_NAME=cthread  WITH_THREAD=cthread  WITH_DISTRIBUTED=serial
    - BUILD_NAME=tbb      WITH_THREAD=tbb      WITH_DISTRIBUTED=serial
    # test mpi
    - BUILD_NAME=mpi      WITH_THREAD=cthread  WITH_DISTRIBUTED=mpi
    - BUILD_NAME=mpitbb   WITH_THREAD=tbb      WITH_DISTRIBUTED=mpi

before_install:
    - CC=gcc-5
    - CXX=g++-5

before_script: 
    - source ./scripts/travis/check-git-clang-format-output.sh

script:
    - source ./scripts/travis/build.sh

